name: medicine_manager
description: "A new Flutter project."


publish_to: 'none' #


environment:
  sdk: ^3.5.4
  flutter: ^3.24.4


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  flutter_native_splash: ^2.4.2
  flutter_riverpod: ^2.6.1
  gap: ^3.0.1
  font_awesome_flutter: ^10.8.0
  ionicons: ^0.2.2
  image_picker: ^1.1.2
  day_night_time_picker: ^1.3.1
  drop_down_list: ^0.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  intl: ^0.19.0
  weekly_date_picker: ^1.4.2
  calendar_date_picker2: ^1.1.7
  modal_bottom_sheet: ^3.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#154FE3"
  color_dark: "#154FE3"
  image: "assets/logo.jpg"

  android_12:
    color: "#084059"
    color_dark: "#084059"
    image: "assets/logo.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/