// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDDuG2aT8OmWzVaQEvE8Ot6-5Bl0FSUc',
    appId: '1:974990610715:web:8ed931ec5bf8f03029c3be',
    messagingSenderId: '974990610715',
    projectId: 'medical-app-f9f81',
    authDomain: 'medical-app-f9f81.firebaseapp.com',
    databaseURL: 'https://medical-app-f9f81-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-f9f81.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQCDhapotGRVxwiYqJ4k2fI227WnUsEKU',
    appId: '1:974990610715:android:c06a3c235c1b303129c3be',
    messagingSenderId: '974990610715',
    projectId: 'medical-app-f9f81',
    databaseURL: 'https://medical-app-f9f81-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-f9f81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgevk16bJ8jayHo0ZIjWzSiVMWZeKAMMA',
    appId: '1:974990610715:ios:5d35d23e4640aacf29c3be',
    messagingSenderId: '974990610715',
    projectId: 'medical-app-f9f81',
    databaseURL: 'https://medical-app-f9f81-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-f9f81.firebasestorage.app',
    iosBundleId: 'com.example.medicineManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgevk16bJ8jayHo0ZIjWzSiVMWZeKAMMA',
    appId: '1:974990610715:ios:5d35d23e4640aacf29c3be',
    messagingSenderId: '974990610715',
    projectId: 'medical-app-f9f81',
    databaseURL: 'https://medical-app-f9f81-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-f9f81.firebasestorage.app',
    iosBundleId: 'com.example.medicineManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoDDuG2aT8OmWzVaQEvE8Ot6-5Bl0FSUc',
    appId: '1:974990610715:web:3e45b7097ec6188d29c3be',
    messagingSenderId: '974990610715',
    projectId: 'medical-app-f9f81',
    authDomain: 'medical-app-f9f81.firebaseapp.com',
    databaseURL: 'https://medical-app-f9f81-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'medical-app-f9f81.firebasestorage.app',
  );
}
